# minio
services:
  minio:
    image: minio/minio
    container_name: minio
    restart: always
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: $MINIO_ACCESS_KEY
      MINIO_SECRET_KEY: $MINIO_SECRET_KEY
    volumes:
      - ./data:/data
    command: server /data --console-address ":9001"
